# Generated by Django 3.0.8 on 2021-01-08 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210102_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Active', models.CharField(max_length=10)),
                ('Stud_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Student')),
            ],
        ),
    ]
