# Generated by Django 3.0.8 on 2021-01-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_attandance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandance',
            name='Reason',
            field=models.TextField(null=True),
        ),
    ]
