# Generated by Django 3.0.8 on 2021-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210109_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandance',
            name='Course',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
